#!/usr/bin/env bash
# =============================================================================
# omp-mc install.sh — Maas Creative oh-my-pi distribution setup
# Usage: ./install.sh
# Re-run anytime after editing models.env to apply changes.
# =============================================================================
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$REPO_DIR/models.env"
OMP_RULES_DIR="$HOME/.omp/rules"
OMP_AGENTS_DIR="$HOME/.omp/agent/agents"
ZSHRC="$HOME/.zshrc"
MARKER="# >>> omp-mc config >>>"
MARKER_END="# <<< omp-mc config <<<"

# --- Load config ---
if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ models.env not found. Copy models.env.example to models.env and edit it."
  exit 1
fi
source "$CONFIG_FILE"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║        omp-mc Installer (Maas Creative)      ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# =============================================================================
# 1. Audit OSS tools
# =============================================================================
echo "🔍 Checking audit tools..."
MISSING=()
for cmd in cucumber-js spectral depcruise stryker; do
  command -v "$cmd" &>/dev/null || MISSING+=("$cmd")
done
if [ ${#MISSING[@]} -gt 0 ]; then
  echo "📦 Installing: ${MISSING[*]}"
  npm install -g @cucumber/cucumber @stoplight/spectral-cli dependency-cruiser stryker-cli
else
  echo "✅ All audit tools installed."
fi

# =============================================================================
# 2. Remote Agent
# =============================================================================
echo ""
echo "🌐 Setting up remote access..."

if [ "${REMOTE_MODE:-tailscale}" = "disabled" ]; then
  echo "   ⏭  Remote mode is 'disabled' in models.env. Skipping."
else
  # Install remote-agent
  if ! command -v remote-agent &>/dev/null; then
    echo "📦 Installing @kimuson/remote-agent globally..."
    npm install -g @kimuson/remote-agent
  else
    echo "✅ @kimuson/remote-agent already installed."
  fi

  # Determine mode
  EFFECTIVE_MODE="${REMOTE_MODE:-tailscale}"
  if [ "$EFFECTIVE_MODE" = "tailscale" ] && ! command -v tailscale &>/dev/null; then
    echo "   ⚠️  Tailscale not found — falling back to 'lan' mode."
    echo "       Install Tailscale: https://tailscale.com/download"
    EFFECTIVE_MODE="lan"
  fi

  # Build launch flags
  case "$EFFECTIVE_MODE" in
    tailscale)
      RA_FLAGS="--tailscale"
      if [ "${REMOTE_TAILSCALE_FUNNEL:-false}" = "true" ]; then
        RA_FLAGS="$RA_FLAGS --funnel"
      fi
      echo "   ✅ Remote mode: Tailscale (HTTPS + VPN)"
      ;;
    lan)
      RA_FLAGS="--same-lan"
      echo "   ✅ Remote mode: LAN only"
      ;;
  esac
fi

# =============================================================================
# 3. Rules & Agents symlinks
# =============================================================================
echo ""
echo "📁 Setting up ~/.omp directories..."
mkdir -p "$OMP_RULES_DIR" "$OMP_AGENTS_DIR"

echo "🔗 Linking rules..."
for f in "$REPO_DIR"/.omp/rules/*.md; do
  ln -sf "$f" "$OMP_RULES_DIR/$(basename "$f")"
  echo "   → $(basename "$f")"
done

echo "🔗 Linking agents..."
for f in "$REPO_DIR"/.omp/agents/*.md; do
  ln -sf "$f" "$OMP_AGENTS_DIR/$(basename "$f")"
  echo "   → $(basename "$f")"
done

# =============================================================================
# 4. Write to ~/.zshrc (idempotent)
# =============================================================================
echo ""
echo "⚙️  Configuring ~/.zshrc..."

if grep -q "$MARKER" "$ZSHRC" 2>/dev/null; then
  sed -i '' "/$MARKER/,/$MARKER_END/d" "$ZSHRC"
fi

# Build omp-remote alias
if [ "${REMOTE_MODE:-tailscale}" != "disabled" ]; then
  ALIAS_CMD="npx @kimuson/remote-agent serve ${RA_FLAGS} --port \${REMOTE_PORT:-44444} -- omp acp"
  REMOTE_ALIAS="alias omp-remote='$ALIAS_CMD'"
else
  REMOTE_ALIAS="# omp-remote disabled (set REMOTE_MODE in models.env)"
fi

cat >> "$ZSHRC" <<EOF

$MARKER
# Auto-generated by omp-mc/install.sh
# To change settings: edit models.env and re-run ./install.sh

# Model assignments
[ -f "$REPO_DIR/models.env" ] && source "$REPO_DIR/models.env"

# Remote access
$REMOTE_ALIAS
$MARKER_END
EOF

echo "   ✅ ~/.zshrc updated"

# =============================================================================
# 5. Done
# =============================================================================
source "$CONFIG_FILE"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║            ✅ Setup Complete!                ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  🧠 PI_SLOW_MODEL  = ${PI_SLOW_MODEL}"
echo "  📐 PI_PLAN_MODEL  = ${PI_PLAN_MODEL}"
echo "  ⚡ PI_SMOL_MODEL  = ${PI_SMOL_MODEL}"
echo "  🌐 REMOTE_MODE    = ${REMOTE_MODE} (port: ${REMOTE_PORT})"
echo ""
echo "  📡 Start remote access:  omp-remote"
echo "  💡 Change settings:      nano models.env && ./install.sh"
echo ""
