#!/usr/bin/env bash
set -eo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$REPO_DIR/models.env"
ZSHRC="$HOME/.zshrc"
OMP_ENV="$HOME/.omp/.env"
MARKER="# >>> omp-mc config >>>"
MARKER_END="# <<< omp-mc config <<<"

[ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"

echo "🔧 Installing omp-mc (MaaS Creative Distribution)..."

# 1. Sync configuration
mkdir -p "$(dirname "$OMP_ENV")"
cat > "$OMP_ENV" << ENVEOF
# Generated by omp-mc install.sh
OPENCODE_API_KEY="$OPENCODE_API_KEY"
OPENCODE_KEY="$OPENCODE_API_KEY"
OPENCODE_TOKEN="$OPENCODE_API_KEY"
OPENCODE_GO_API_KEY="$OPENCODE_API_KEY"
ZENMUX_API_KEY="$OPENCODE_API_KEY"
PI_SLOW_MODEL="$PI_SLOW_MODEL"
PI_PLAN_MODEL="$PI_PLAN_MODEL"
PI_SMOL_MODEL="$PI_SMOL_MODEL"
PI_MODEL="$PI_SLOW_MODEL"
ENVEOF

# 2. Symlinks
mkdir -p "$HOME/.omp/rules" "$HOME/.omp/agent/agents"
for f in "$REPO_DIR"/.omp/rules/*.md; do ln -sf "$f" "$HOME/.omp/rules/$(basename "$f")"; done
for f in "$REPO_DIR"/.omp/agents/*.md; do ln -sf "$f" "$HOME/.omp/agent/agents/$(basename "$f")"; done

# 3. Zshrc Update (Wrapper Functions)
if grep -q "$MARKER" "$ZSHRC" 2>/dev/null; then
  sed -i '' "/$MARKER/,/$MARKER_END/d" "$ZSHRC"
fi

cat >> "$ZSHRC" <<EOF

$MARKER
# omp-mc distribution configuration
[ -f "$REPO_DIR/models.env" ] && source "$REPO_DIR/models.env"

# Wrapper for omp to brand the update message
function omp() {
  if [[ "\$*" == "update" ]]; then
    omp-mc update
    return
  fi
  # TUI の案内を置換（インタラクティブ性を損なわないように注意）
  command omp "\$@"
}

# The official entry point for MaaS Creative environment
function omp-mc() {
  case "\$1" in
    update)
      echo "🚀 Updating omp-mc environment..."
      # 1. Update core binary
      command omp update
      # 2. Update omp-mc repository and rules
      (cd "$REPO_DIR" && git pull && ./install.sh)
      echo "✅ omp-mc environment is up to date."
      ;;
    *)
      omp "\$@"
      ;;
  esac
}

# Smart remote launcher
unalias omp-mc-remote 2>/dev/null
function omp-mc-remote() {
  local port=\${REMOTE_PORT:-44444}
  local pids=\$(lsof -i tcp:\$port -sTCP:LISTEN -t 2>/dev/null || true)
  if [ -n "\$pids" ]; then
    echo "⚠️ Port \$port is in use. Killing \$pids..."
    echo \$pids | xargs kill -9
    sleep 2
  fi
  npx @kimuson/remote-agent serve \${REMOTE_MODE:---tailscale} --port \$port
}

function omc-init() {
  npx -y npm-add-script -k "audit" -v "cucumber-js && depcruise src && npm audit"
  echo "✅ Audit scripts added to package.json"
}
$MARKER_END
EOF

echo "✅ Setup Complete!"
echo "   ✨ You can now use: omp-mc update"
