#!/usr/bin/env bash
# =============================================================================
# omp-mc install.sh — Maas Creative oh-my-pi distribution setup
# =============================================================================
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OMP_RULES_DIR="$HOME/.omp/rules"
OMP_AGENTS_DIR="$HOME/.omp/agent/agents"
ZSHRC="$HOME/.zshrc"
MARKER="# >>> omp-mc model config >>>"
MARKER_END="# <<< omp-mc model config <<<"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║        omp-mc Installer (Maas Creative)      ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# 1. グローバルOSSツールの確認
echo "🔍 Checking required OSS tools..."
MISSING=()
for cmd in cucumber-js spectral depcruise stryker; do
  command -v "$cmd" &>/dev/null || MISSING+=("$cmd")
done
if [ ${#MISSING[@]} -gt 0 ]; then
  echo "📦 Installing: ${MISSING[*]}"
  npm install -g @cucumber/cucumber @stoplight/spectral-cli dependency-cruiser stryker-cli
else
  echo "✅ All audit tools are installed."
fi

# 2. ~/.omp ディレクトリ作成
echo ""
echo "📁 Setting up ~/.omp directories..."
mkdir -p "$OMP_RULES_DIR" "$OMP_AGENTS_DIR"

# 3. rules & agents のシンボリックリンク
echo "🔗 Linking rules and agents..."
for f in "$REPO_DIR"/.omp/rules/*.md; do
  ln -sf "$f" "$OMP_RULES_DIR/$(basename "$f")"
  echo "   → rule: $(basename "$f")"
done
for f in "$REPO_DIR"/.omp/agents/*.md; do
  ln -sf "$f" "$OMP_AGENTS_DIR/$(basename "$f")"
  echo "   → agent: $(basename "$f")"
done

# 4. models.env を ~/.zshrc に登録（冪等）
echo ""
echo "⚙️  Configuring model assignments in ~/.zshrc..."
if grep -q "$MARKER" "$ZSHRC" 2>/dev/null; then
  sed -i '' "/$MARKER/,/$MARKER_END/d" "$ZSHRC"
fi
cat >> "$ZSHRC" <<EOF

$MARKER
# Auto-generated by omp-mc/install.sh — edit models.env to change models.
[ -f "$REPO_DIR/models.env" ] && source "$REPO_DIR/models.env"
$MARKER_END
EOF
echo "   ✅ Written to ~/.zshrc"

# 5. 現在のシェルに即時反映
source "$REPO_DIR/models.env"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║            ✅ Setup Complete!                ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  🧠 PI_SLOW_MODEL = $PI_SLOW_MODEL"
echo "  📐 PI_PLAN_MODEL = $PI_PLAN_MODEL"
echo "  ⚡ PI_SMOL_MODEL = $PI_SMOL_MODEL"
echo ""
echo "  💡 To change models: edit 'models.env' then run './install.sh' again."
