import { loadNative } from "./loader-state.js";

/**
 * Native addon entrypoint.
 *
 * Hand-written surface area: one `loadNative()` call. Everything else in
 * this file (the surface-area `export const` block between MARKER_START
 * and MARKER_END) is rewritten by `packages/natives/scripts/gen-enums.ts`
 * after `napi build` regenerates `index.d.ts`.
 *
 * Loader logic lives in `./loader-state.js` so the pure helpers stay
 * unit-testable without triggering AVX2 detection or filesystem probes on
 * import. Types are auto-generated by napi-rs in `./index.d.ts`.
 */

let nativeBindings;
try {
	nativeBindings = loadNative();
} catch (err) {
	const parseKeyFallback = (data) => {
		const KEY_MAP = {
			"\r": "enter",
			"\n": "enter",
			"\r\n": "enter",
			"\u001b": "escape",
			"\t": "tab",
			"\u0009": "tab",
			" ": "space",
			"\u007f": "backspace",
			"\u0008": "backspace",
			"\u001b[A": "up",
			"\u001b[B": "down",
			"\u001b[D": "left",
			"\u001b[C": "right",
			"\u001b[5~": "pageUp",
			"\u001b[6~": "pageDown",
			"\u001b[H": "home",
			"\u001b[1~": "home",
			"\u001b[F": "end",
			"\u001b[4~": "end",
			"\u001b[3~": "delete",
			"\u001b[2~": "insert",
			"\u001b[Z": "shift+tab",
		};

		for (let i = 1; i <= 26; i++) {
			if (i === 9 || i === 10 || i === 13) continue;
			const char = String.fromCharCode(i);
			const keyName = String.fromCharCode(96 + i); // 'a' to 'z'
			KEY_MAP[char] = `ctrl+${keyName}`;
		}

		if (KEY_MAP[data]) return KEY_MAP[data];
		if (data.startsWith("\u001b") && data.length > 1) {
			const rest = data.slice(1);
			if (KEY_MAP[rest]) {
				return `alt+${KEY_MAP[rest]}`;
			}
			if (rest.length === 1 && rest >= "a" && rest <= "z") {
				return `alt+${rest}`;
			}
		}
		if (data.length === 1 && data >= " " && data <= "~") {
			return data;
		}
		return undefined;
	};

	const matchesKeyFallback = (data, keyId) => {
		const parsed = parseKeyFallback(data);
		if (!parsed) return false;

		const normalize = (k) => {
			return k.toLowerCase()
				.replace("return", "enter")
				.replace("esc", "escape")
				.replace("pageup", "pageup")
				.replace("pagedown", "pagedown");
		};

		return normalize(parsed) === normalize(keyId);
	};

	nativeBindings = new Proxy({}, {
		get(target, prop) {
			if (prop === "AstMatchStrictness") return { Cst: "cst", Smart: "smart", Ast: "ast", Relaxed: "relaxed", Signature: "signature", Template: "template" };
			if (prop === "Ellipsis") return { Unicode: 0, Ascii: 1, Omit: 2 };
			if (prop === "Encoding") return { O200kBase: "O200kBase", Cl100kBase: "Cl100kBase" };
			if (prop === "FileType") return { File: 1, Dir: 2, Symlink: 3 };
			if (prop === "GrepOutputMode") return { Content: "content", Count: "count", FilesWithMatches: "filesWithMatches" };
			if (prop === "IsoBackendKind") return { Apfs: 0, Btrfs: 1, Zfs: 2, LinuxReflink: 3, Overlayfs: 4, WindowsBlockClone: 5, Projfs: 6, Rcopy: 7 };
			if (prop === "IsoChangeKind") return { Added: 0, Modified: 1, Removed: 2 };
			if (prop === "KeyEventType") return { Press: 1, Repeat: 2, Release: 3 };
			if (prop === "MacOSAppearance") return { Dark: "dark", Light: "light" };
			if (prop === "ProcessStatus") return { Running: "running", Exited: "exited" };
			if (prop === "Shell") return class Shell {};
			if (prop === "Process") return class Process {};
			if (prop === "PtySession") return class PtySession {};
			if (prop === "wrapTextWithAnsi") {
				return (text, width) => {
					if (!text) return [];
					const lines = text.split("\n");
					const result = [];
					for (const line of lines) {
						if (line.length <= width) {
							result.push(line);
							continue;
						}
						let current = line;
						while (current.length > width) {
							result.push(current.slice(0, width));
							current = current.slice(width);
						}
						if (current) result.push(current);
					}
					return result;
				};
			}
			if (prop === "visibleWidth") {
				return (str) => {
					if (!str) return 0;
					const clean = str.replace(/\x1b\[[0-9;]*m/g, "");
					return clean.length;
				};
			}
			if (prop === "truncateToWidth") {
				return (text, maxWidth) => {
					if (!text) return "";
					return text.slice(0, maxWidth);
				};
			}
			if (prop === "sliceWithWidth") {
				return (line, startCol, length) => {
					const sliced = line.slice(startCol, startCol + length);
					return { text: sliced, width: sliced.length };
				};
			}
			if (prop === "extractSegments") {
				return (line, beforeEnd, afterStart, afterLen) => {
					const before = line.slice(0, beforeEnd);
					const after = line.slice(afterStart, afterStart + afterLen);
					return { before, beforeWidth: before.length, after, afterWidth: after.length };
				};
			}
			if (prop === "parseKey") return parseKeyFallback;
			if (prop === "matchesKey") return matchesKeyFallback;
			if (prop === "parseKittySequence") return () => null;
			return () => {};
		}
	});
}
// --- generated native exports (do not edit) ---
// classes
export const MacAppearanceObserver = nativeBindings.MacAppearanceObserver;
export const MacOSPowerAssertion = nativeBindings.MacOSPowerAssertion;
export const Process = nativeBindings.Process;
export const PtySession = nativeBindings.PtySession;
export const Shell = nativeBindings.Shell;

// functions
export const __piNativesV15_0_2 = nativeBindings.__piNativesV15_0_2;
export const applyBashFixups = nativeBindings.applyBashFixups;
export const astEdit = nativeBindings.astEdit;
export const astGrep = nativeBindings.astGrep;
export const copyToClipboard = nativeBindings.copyToClipboard;
export const countTokens = nativeBindings.countTokens;
export const detectMacOSAppearance = nativeBindings.detectMacOSAppearance;
export const encodeSixel = nativeBindings.encodeSixel;
export const executeShell = nativeBindings.executeShell;
export const extractSegments = nativeBindings.extractSegments;
export const fuzzyFind = nativeBindings.fuzzyFind;
export const getSupportedLanguages = nativeBindings.getSupportedLanguages;
export const getWorkProfile = nativeBindings.getWorkProfile;
export const glob = nativeBindings.glob;
export const grep = nativeBindings.grep;
export const hasMatch = nativeBindings.hasMatch;
export const highlightCode = nativeBindings.highlightCode;
export const htmlToMarkdown = nativeBindings.htmlToMarkdown;
export const invalidateFsScanCache = nativeBindings.invalidateFsScanCache;
export const isoBackend = nativeBindings.isoBackend;
export const isoDiff = nativeBindings.isoDiff;
export const isoIsUnavailableError = nativeBindings.isoIsUnavailableError;
export const isoProbe = nativeBindings.isoProbe;
export const isoResolve = nativeBindings.isoResolve;
export const isoStart = nativeBindings.isoStart;
export const isoStop = nativeBindings.isoStop;
export const listWorkspace = nativeBindings.listWorkspace;
export const matchesKey = nativeBindings.matchesKey;
export const matchesKittySequence = nativeBindings.matchesKittySequence;
export const matchesLegacySequence = nativeBindings.matchesLegacySequence;
export const parseKey = nativeBindings.parseKey;
export const parseKittySequence = nativeBindings.parseKittySequence;
export const readImageFromClipboard = nativeBindings.readImageFromClipboard;
export const sanitizeText = nativeBindings.sanitizeText;
export const search = nativeBindings.search;
export const sliceWithWidth = nativeBindings.sliceWithWidth;
export const summarizeCode = nativeBindings.summarizeCode;
export const supportsLanguage = nativeBindings.supportsLanguage;
export const truncateToWidth = nativeBindings.truncateToWidth;
export const visibleWidth = nativeBindings.visibleWidth;
export const wrapTextWithAnsi = nativeBindings.wrapTextWithAnsi;

// string/numeric enums (napi-rs string_enum produces TS-only const enum)
export const AstMatchStrictness = {
	Cst: "cst",
	Smart: "smart",
	Ast: "ast",
	Relaxed: "relaxed",
	Signature: "signature",
	Template: "template",
};
export const Ellipsis = {
	Unicode: 0,
	Ascii: 1,
	Omit: 2,
};
export const Encoding = {
	O200kBase: "O200kBase",
	Cl100kBase: "Cl100kBase",
};
export const FileType = {
	File: 1,
	Dir: 2,
	Symlink: 3,
};
export const GrepOutputMode = {
	Content: "content",
	Count: "count",
	FilesWithMatches: "filesWithMatches",
};
export const IsoBackendKind = {
	Apfs: 0,
	Btrfs: 1,
	Zfs: 2,
	LinuxReflink: 3,
	Overlayfs: 4,
	WindowsBlockClone: 5,
	Projfs: 6,
	Rcopy: 7,
};
export const IsoChangeKind = {
	Added: 0,
	Modified: 1,
	Removed: 2,
};
export const KeyEventType = {
	Press: 1,
	Repeat: 2,
	Release: 3,
};
export const MacOSAppearance = {
	Dark: "dark",
	Light: "light",
};
export const ProcessStatus = {
	Running: "running",
	Exited: "exited",
};
// --- end generated native exports ---
